# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb0ccdf1b204bec05ad38afd56bd95825f4c46b021c051adaa81ac29267dd4e63baf1e7e6a51c27c1a696b5d49b6c974d56530baaf0d42faa28d6d657a7f50f5

test:
  secret_key_base: 099b8522773d1ecdd3a2a20298dd0045e00c03c5a9d2944a998a22a68b525fae3f134105d5f8279407932cbd441e98eec6106635fa4ce17d876e3fd3b7be896d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
